[preload  storage="./data/bgimage/black-screen.png"  ]
[preload  storage="./data/bgimage/shopping-mall_entrance.png"  ]
[preload  storage="./data/fgimage/chara/3/コタニ③爆笑.png"  ]
[preload  storage="./data/fgimage/chara/4/リナ①通常.png"  ]
[preload  storage="./data/fgimage/chara/4/リナ④ドン引き.png"  ]
[preload  storage="./data/fgimage/chara/4/リナ②孤独.png"  ]
[preload  storage="./data/fgimage/chara/3/コタニ②笑顔.png"  ]
[preload  storage="./data/fgimage/chara/4/リナ③笑う.png"  ]
[preload  storage="./data/fgimage/default/kotani_cleaning.png"  ]
[preload  storage="./data/fgimage/default/rina_arcade.png"  ]
[preload  storage="./data/fgimage/chara/3/コタニ⑥饒舌.png"  ]
[return]