[preload  storage="./data/bgimage/水槽部屋②.png"  ]
[preload  storage="./data/fgimage/chara/5/魚の悪霊②.png"  ]
[preload  storage="./data/fgimage/chara/5/魚の悪霊①.png"  ]
[preload  storage="./data/fgimage/chara/5/魚の悪霊③.png"  ]
[preload  storage="./data/bgimage/リナの心の世界（倉庫②）.png"  ]
[preload  storage="./data/bgimage/リナの心の世界（倉庫③）.png"  ]
[preload  storage="./data/bgimage/リナの心の世界（倉庫④）.png"  ]
[return]