[eval exp="f._system_preview_ks='chapter101.ks'"] 
[preload  storage="./data/bgimage/最高会議室前.png"  ]
[preload  storage="./data/fgimage/default/スクリーン①.png"  ]
[preload  storage="./data/fgimage/default/スクリーン②.png"  ]
[return] 